### ISSUE TITLE
Virtual Box 7.0

### ISSUE THREAD

**Issue by al8n** [dogukancagatay/fedora-boxes-aarch64#2]
Hi, thanks for the boxes. As the virtual box 7.0 beta supports Mac M1, does these boxes work on virtual box?

**Comment by dogukancagatay** [comment]
The boxes on Vagrant Cloud are tested and built for Parallels Desktop provider only. They won't directly work on the VirtualBox.

However, if you manually convert the boxes to VirtualBox, it might work. The proper way is creating and building Packer templates for the VirtualBox.
